# Generated by Django 5.1 on 2024-09-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs_model',
            name='blog_files',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
