# Generated by Django 5.1 on 2024-09-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connect', '0003_alter_blogs_model_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs_model',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
