# Generated by Django 5.1 on 2024-09-03 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connect', '0004_alter_blogs_model_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs_model',
            name='blog_files',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blogs_model',
            name='blog_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
